owner: thejord-it
repo: status

sites:
  - name: API
    url: https://api.rollgate.io/health
    expectedStatusCodes:
      - 200

  - name: Dashboard
    url: https://app.rollgate.io
    expectedStatusCodes:
      - 200

  - name: Demo
    url: https://demo.rollgate.io
    expectedStatusCodes:
      - 200

  - name: SSE Endpoint
    url: https://sse.rollgate.io/health
    expectedStatusCodes:
      - 200
      - 404

  - name: SDK Flags
    url: https://api.rollgate.io/api/v1/sdk/flags
    expectedStatusCodes:
      - 401

status-website:
  cname: status.rollgate.io
  logoUrl: https://app.rollgate.io/logo.svg
  name: Rollgate Status
  theme: light
  introTitle: "Rollgate System Status"
  introMessage: "Real-time and historical uptime for Rollgate services."

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/5 * * * *"

i18n:
  activeIncidents: Active incidents
  allSystemsOperational: All systems operational
  incidentReport: "Incident report for {0}"
  incidentDetails: Incident details
  noIncidents: No incidents reported
  pastIncidents: Past incidents
  subscribeBySMS: Subscribe to SMS alerts
  subscribeByEmail: Subscribe to email alerts
  liveStatus: Live status
  overallUptime: "uptime"
  overallResponseTime: "response time"
  day: day
  days: days
  ms: ms
  loading: Loading...
  navStatus: Status
  navGitHub: GitHub
